---
abstract: 'Manipulate Open Packaging Conventions files.'
author:
  - 'Douglas Christopher Wilson <doug@somethingdoug.com>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  File::Spec: 0
  Test::More: 0.88
  URI: 0.07
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: File-OPC
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  List::Util: 1.18
  MIME::Type: 1.24
  Moose: 0.74
  Moose::Util::TypeConstraints: 0
  MooseX::StrictConstructor: 0.08
  MooseX::Types: 0.08
  Readonly: 1.03
  Sub::Exporter: 0.980
  Sub::Name: 0
  URI: 0.07
  XML::XPath: 1.13
  namespace::clean: 0.04
  perl: 5.8.1
resources:
  license: http://dev.perl.org/licenses/
version: 0.001
